import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faStar,
  faStarHalfStroke,
  faHeart,
  faHeartPulse,
  faHandHoldingHeart,
  faCertificate,
  faBurst,
  faStarOfLife,
  faSnowflake,
  faAsterisk,
  faHashtag,
  faAt,
  faPlus,
  faMinus,
  faXmark,
  faCheck,
  faEquals,
  faExclamation,
  faQuestion,
  faCircle,
  faSquare,
  faSquareFull,
  faDiamond,
  faShapes,
  faClover,
  faSpa,
  faYinYang,
  faPeace,
  faBahai,
  faRecycle,
  faInfinity,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faRotate,
  faReply,
  faShare,
  faLocationArrow,
  faAnglesRight,
  faChevronRight,
  faCaretRight,
  faArrowsUpDown,
  faArrowsSpin,
  faShuffle,
  faCloud,
  faBolt,
  faSun,
  faMoon,
  faCloudSun,
  faCloudMoon,
  faCloudRain,
  faCloudShowersHeavy,
  faFire,
  faFireFlameCurved,
  faLeaf,
  faSeedling,
  faTree,
  faFeather,
  faFeatherPointed,
  faWind,
  faRainbow,
  faMountain,
  faMeteor,
  faTornado,
  faUmbrella,
  faDroplet,
  faSnowman,
  faPaw,
  faCat,
  faDog,
  faFish,
  faDove,
  faCrow,
  faDragon,
  faSpider,
  faHorse,
  faFrog,
  faKiwiBird,
  faBug,
  faShrimp,
  faOtter,
  faHippo,
  faSpaghettiMonsterFlying,
  faDisease,
  faWorm,
  faAppleWhole,
  faCarrot,
  faLemon,
  faPepperHot,
  faIceCream,
  faCookie,
  faCookieBite,
  faCakeCandles,
  faPizzaSlice,
  faMugHot,
  faMugSaucer,
  faWineGlass,
  faMartiniGlass,
  faCandyCane,
  faBowlFood,
  faBurger,
  faHotdog,
  faDrumstickBite,
  faEgg,
  faCheese,
  faStroopwafel,
  faGift,
  faGifts,
  faCrown,
  faGem,
  faRing,
  faChessKnight,
  faPuzzlePiece,
  faDice,
  faDiceFive,
  faGamepad,
  faGhost,
  faRobot,
  faRocket,
  faPlane,
  faCar,
  faBicycle,
  faAnchor,
  faCompass,
  faMap,
  faKey,
  faLightbulb,
  faMagnet,
  faPaintbrush,
  faPalette,
  faBrush,
  faPenNib,
  faPencil,
  faStamp,
  faGuitar,
  faDrum,
  faMusic,
  faHeadphones,
  faBell,
  faBullhorn,
  faCamera,
  faClapperboard,
  faFilm,
  faTicket,
  faTrophy,
  faMedal,
  faAward,
  faFlask,
  faAtom,
  faDna,
  faMicroscope,
  faMagnifyingGlass,
  faBookOpen,
  faBook,
  faGraduationCap,
  faPaperPlane,
  faEnvelope,
  faComment,
  faComments,
  faCommentDots,
  faThumbsUp,
  faHandSpock,
  faHandPeace,
  faFaceSmile,
  faFaceLaugh,
  faFaceGrinStars,
  faFaceMeh,
  faWandMagicSparkles,
  faWandSparkles,
  faHatWizard,
  faHandSparkles,
  faStarAndCrescent,
  faShieldHalved,
  faShield,
  faSkull,
  faSkullCrossbones,
  faBomb,
  faBan,
  faBullseye,
  faCircleDot,
  faCirclePlay,
  faCircleCheck,
  faSleigh,
  faHollyBerry,
  faChurch,
  faMosque,
  faClock,
  faHourglass,
  faStopwatch,
  faCompactDisc,
  faCrosshairs,
  faCubesStacked,
  faCube,
  faCubes,
  faDiceD20,
  faChessQueen,
  faChessRook,
  faGopuram,
} from "@fortawesome/free-solid-svg-icons";

/** Curated set of Font Awesome figures usable in backgrounds, keyed by name. */
const DEFS: Record<string, IconDefinition> = {
  "star": faStar,
  "star-half-stroke": faStarHalfStroke,
  "heart": faHeart,
  "heart-pulse": faHeartPulse,
  "hand-holding-heart": faHandHoldingHeart,
  "certificate": faCertificate,
  "burst": faBurst,
  "star-of-life": faStarOfLife,
  "snowflake": faSnowflake,
  "asterisk": faAsterisk,
  "hashtag": faHashtag,
  "at": faAt,
  "plus": faPlus,
  "minus": faMinus,
  "xmark": faXmark,
  "check": faCheck,
  "equals": faEquals,
  "exclamation": faExclamation,
  "question": faQuestion,
  "circle": faCircle,
  "square": faSquare,
  "square-full": faSquareFull,
  "diamond": faDiamond,
  "shapes": faShapes,
  "clover": faClover,
  "spa": faSpa,
  "yin-yang": faYinYang,
  "peace": faPeace,
  "bahai": faBahai,
  "recycle": faRecycle,
  "infinity": faInfinity,
  "arrow-right": faArrowRight,
  "arrow-left": faArrowLeft,
  "arrow-up": faArrowUp,
  "arrow-down": faArrowDown,
  "rotate": faRotate,
  "reply": faReply,
  "share": faShare,
  "location-arrow": faLocationArrow,
  "angles-right": faAnglesRight,
  "chevron-right": faChevronRight,
  "caret-right": faCaretRight,
  "arrows-up-down": faArrowsUpDown,
  "arrows-spin": faArrowsSpin,
  "shuffle": faShuffle,
  "cloud": faCloud,
  "bolt": faBolt,
  "sun": faSun,
  "moon": faMoon,
  "cloud-sun": faCloudSun,
  "cloud-moon": faCloudMoon,
  "cloud-rain": faCloudRain,
  "cloud-showers-heavy": faCloudShowersHeavy,
  "fire": faFire,
  "fire-flame-curved": faFireFlameCurved,
  "leaf": faLeaf,
  "seedling": faSeedling,
  "tree": faTree,
  "feather": faFeather,
  "feather-pointed": faFeatherPointed,
  "wind": faWind,
  "rainbow": faRainbow,
  "mountain": faMountain,
  "meteor": faMeteor,
  "tornado": faTornado,
  "umbrella": faUmbrella,
  "droplet": faDroplet,
  "snowman": faSnowman,
  "paw": faPaw,
  "cat": faCat,
  "dog": faDog,
  "fish": faFish,
  "dove": faDove,
  "crow": faCrow,
  "dragon": faDragon,
  "spider": faSpider,
  "horse": faHorse,
  "frog": faFrog,
  "kiwi-bird": faKiwiBird,
  "bug": faBug,
  "shrimp": faShrimp,
  "otter": faOtter,
  "hippo": faHippo,
  "spaghetti-monster-flying": faSpaghettiMonsterFlying,
  "disease": faDisease,
  "worm": faWorm,
  "apple-whole": faAppleWhole,
  "carrot": faCarrot,
  "lemon": faLemon,
  "pepper-hot": faPepperHot,
  "ice-cream": faIceCream,
  "cookie": faCookie,
  "cookie-bite": faCookieBite,
  "cake-candles": faCakeCandles,
  "pizza-slice": faPizzaSlice,
  "mug-hot": faMugHot,
  "mug-saucer": faMugSaucer,
  "wine-glass": faWineGlass,
  "martini-glass": faMartiniGlass,
  "candy-cane": faCandyCane,
  "bowl-food": faBowlFood,
  "burger": faBurger,
  "hotdog": faHotdog,
  "drumstick-bite": faDrumstickBite,
  "egg": faEgg,
  "cheese": faCheese,
  "stroopwafel": faStroopwafel,
  "gift": faGift,
  "gifts": faGifts,
  "crown": faCrown,
  "gem": faGem,
  "ring": faRing,
  "chess-knight": faChessKnight,
  "puzzle-piece": faPuzzlePiece,
  "dice": faDice,
  "dice-five": faDiceFive,
  "gamepad": faGamepad,
  "ghost": faGhost,
  "robot": faRobot,
  "rocket": faRocket,
  "plane": faPlane,
  "car": faCar,
  "bicycle": faBicycle,
  "anchor": faAnchor,
  "compass": faCompass,
  "map": faMap,
  "key": faKey,
  "lightbulb": faLightbulb,
  "magnet": faMagnet,
  "paintbrush": faPaintbrush,
  "palette": faPalette,
  "brush": faBrush,
  "pen-nib": faPenNib,
  "pencil": faPencil,
  "stamp": faStamp,
  "guitar": faGuitar,
  "drum": faDrum,
  "music": faMusic,
  "headphones": faHeadphones,
  "bell": faBell,
  "bullhorn": faBullhorn,
  "camera": faCamera,
  "clapperboard": faClapperboard,
  "film": faFilm,
  "ticket": faTicket,
  "trophy": faTrophy,
  "medal": faMedal,
  "award": faAward,
  "flask": faFlask,
  "atom": faAtom,
  "dna": faDna,
  "microscope": faMicroscope,
  "magnifying-glass": faMagnifyingGlass,
  "book-open": faBookOpen,
  "book": faBook,
  "graduation-cap": faGraduationCap,
  "paper-plane": faPaperPlane,
  "envelope": faEnvelope,
  "comment": faComment,
  "comments": faComments,
  "comment-dots": faCommentDots,
  "thumbs-up": faThumbsUp,
  "hand-spock": faHandSpock,
  "hand-peace": faHandPeace,
  "face-smile": faFaceSmile,
  "face-laugh": faFaceLaugh,
  "face-grin-stars": faFaceGrinStars,
  "face-meh": faFaceMeh,
  "wand-magic-sparkles": faWandMagicSparkles,
  "wand-sparkles": faWandSparkles,
  "hat-wizard": faHatWizard,
  "hand-sparkles": faHandSparkles,
  "star-and-crescent": faStarAndCrescent,
  "shield-halved": faShieldHalved,
  "shield": faShield,
  "skull": faSkull,
  "skull-crossbones": faSkullCrossbones,
  "bomb": faBomb,
  "ban": faBan,
  "bullseye": faBullseye,
  "circle-dot": faCircleDot,
  "circle-play": faCirclePlay,
  "circle-check": faCircleCheck,
  "sleigh": faSleigh,
  "holly-berry": faHollyBerry,
  "church": faChurch,
  "mosque": faMosque,
  "clock": faClock,
  "hourglass": faHourglass,
  "stopwatch": faStopwatch,
  "compact-disc": faCompactDisc,
  "crosshairs": faCrosshairs,
  "cubes-stacked": faCubesStacked,
  "cube": faCube,
  "cubes": faCubes,
  "dice-d20": faDiceD20,
  "chess-queen": faChessQueen,
  "chess-rook": faChessRook,
  "gopuram": faGopuram,
};

export const FIGURE_NAMES = Object.keys(DEFS);

export type FigureGlyph = { width: number; height: number; path: string };

/** Resolve a figure name to its SVG viewBox + path, or null if unknown. */
export function glyph(name: string): FigureGlyph | null {
  const def = DEFS[name];
  if (!def) return null;
  const [width, height, , , path] = def.icon;
  return { width, height, path: Array.isArray(path) ? path[0] : path };
}
